#Create Tomcat Volumes
- name: Create Tomcat Log Volume
  docker_volume:
    name: "{{ tomcat_log_volume_name }}"

- name: Create Tomcat Work Volume
  docker_volume:
    name: "{{ tomcat_work_volume_name }}"

- name: Create Tomcat Catalina Volume
  docker_volume:
    name: "{{ tomcat_catalina_volume_name }}"

- name: Create Tomcat Temp Volume
  docker_volume:
    name: "{{ tomcat_temp_volume_name }}"

- name: build iiq image
  docker_image:
    name: "{{ iiq_image_name }}"
    tag: "{{ iiq_image_tag }}"
    state: present
    source: build
    force_source: "{{ rebuild | ternary ('yes','no') }}"
    build:
      path: "{{ docker_build_context }}"
      dockerfile: "{{ docker_file }}"
      pull: no

- name: Deploy IIQ Container to initialize database
  when: orchestrate
  docker_container:
    name: "{{ iiq_container_name }}"
    image: "{{ iiq_image_name }}:{{ iiq_image_tag }}"
    published_ports:
      - "{{ iiq_app_port }}:{{ iiq_docker_port }}"
    env:
      JAVA_OPTS: "{{ java_opts }}"
    volumes:
      - '{{ playbook_dir }}/iiqdata:/iiqdata'
      - '{{ tomcat_log_volume_name }}:/usr/local/tomcat/logs'
      - '{{ tomcat_work_volume_name }}:/usr/local/tomcat/work'
      - '{{ tomcat_catalina_volume_name }}:/usr/local/tomcat/conf/Catalina'
      - '{{ tomcat_temp_volume_name }}:/usr/local/tomcat/temp'
    networks:
      - name: "{{network_name}}"
    network_mode: "{{network_name}}"
    command: bash
    interactive: yes
    hostname: iiqappserver
    container_default_behavior: compatibility

- name: add iiq image to inventory
  add_host:
    name: "{{ iiq_container_name }}"
    ansible_connection: docker

- name: Wait for Database
  when: orchestrate
  delegate_to: "{{ iiq_container_name }}"
  wait_for:
    host: "{{ db_container_name }}"
    port: "{{ network_db_port }}"
    delay: 5
    timeout: 30
    state: started
    msg: "Database Port is not listining. retrying"
  register: dbup

#Run database specific deployment actions
- name: Create and Patch IIQ Databases
  include_tasks: "{{ db_type }}_deploy.yml"

- name: patch IIQ app
  delegate_to: "{{ iiq_container_name }}"
  when: created_iiq_database.changed and orchestrate
  command: /usr/local/tomcat/webapps/identityiq/WEB-INF/bin/iiq patch {{ iiq_version }}{{ iiq_patch_version }}


- name: Import AP config files
  delegate_to: "{{ iiq_container_name }}"
  when: created_iiq_database.changed and orchestrate and deploy_ap
  shell: "echo 'import init-acceleratorpack.xml' | /usr/local/tomcat/webapps/identityiq/WEB-INF/bin/iiq console"

- name: Import custom config files
  delegate_to: "{{ iiq_container_name }}"
  when: dbup
  shell: "echo 'import sp.init-custom.xml' | /usr/local/tomcat/webapps/identityiq/WEB-INF/bin/iiq console"

- name: deploy iiq
  when: dbup and start_app
  docker_container:
    name: "{{ iiq_container_name }}"
    image: "{{ iiq_image_name }}:{{ iiq_image_tag }}"
    published_ports:
      - "{{ iiq_app_port }}:{{ iiq_docker_port }}"
    env:
      JAVA_OPTS: "{{ java_opts }}"
    volumes:
      - '{{ iiq_data_dir }}:/iiqdata'
      - '{{ tomcat_log_volume_name }}:/usr/local/tomcat/logs'
      - '{{ tomcat_work_volume_name }}:/usr/local/tomcat/work'
      - '{{ tomcat_catalina_volume_name }}:/usr/local/tomcat/conf/Catalina'
      - '{{ tomcat_temp_volume_name }}:/usr/local/tomcat/temp'
    networks:
      - name: "{{network_name}}"
    network_mode: "{{network_name}}"
    restart: yes
    hostname: iiqappserver
    container_default_behavior: compatibility
